// https://dbdiagram.io/

Table Users {
  id string [primary key]
  email string [unique, not null]
  master_salt string [not null]
  srp_salt string [not null]
  srp_verifier string [not null]
  rsa_public_key string [not null]
  encrypted_rsa_private_key string [not null]
  encrypted_rsa_private_key_iv string [not null]
  default_workspace_id string [ref: > Workspaces.id, not null]
  created_at timestamp
  updated_at timestamp
}

Table Workspaces {
  id string [primary key]
  owner_id string [ref: > Users.id, not null]
  name string [not null]
  created_at timestamp
  updated_at timestamp
}

Table WorkspaceMembers {
  workspace_id string [ref: > Workspaces.id, not null]
  user_id string [ref: > Users.id, not null]
  role string [not null, note: '"admin", "manager", "member"']
  created_at timestamp
  
  indexes {
    (workspace_id, user_id) [unique]
  }
}

Table Folders {
  id string [primary key]
  workspace_id string [ref: > Workspaces.id, not null]
  owner_id string [ref: > Users.id, not null]
  name string [not null]
  parent_id string [ref: > Folders.id, note: 'For nested folders']
  created_at timestamp
  updated_at timestamp
}

Table Items {
  id string [primary key]
  folder_id string [ref: > Folders.id, not null]
  owner_id string [ref: > Users.id, not null]
  type string [not null, note: 'Enum: "Login", "Secure Note", etc.']
  display_metadata json
  encrypted_data string [not null]
  encrypted_data_iv string [not null]
  encrypted_record_key string [not null]
  encrypted_record_key_iv string [not null]
  created_at timestamp
  updated_at timestamp
}

Table Shares {
  id string [primary key]
  user_id string [ref: > Users.id, not null]
  
  target_id string [not null]
  target_type string [not null, note: 'Enum: "folder", "item"']
  
  permissions string [not null, note: '"edit", "read-only"']
  
  encrypted_key string [not null]
  
  created_at timestamp
  
  indexes {
    (user_id, target_id, target_type) [unique]
  }
}